#6. Faça um programa que exiba a seguinte receita de bolo de chocolate.
# Exiba um item por vez, conforme a pessoa aperte “enter”.


print("\nIngredientes:")
print("2 xícaras de farinha de trigo")
input()
print("1 xícara de açúcar")
input()
print("1/2 xícara de cacau em pó")
input()
print("1 colher de chá de fermento em pó")
input()
print("1 colher de chá de bicarbonato de sódio")
input()
print("1/2 colher de chá de sal")
input()
print("2 ovos")
input()
print("1 xícara de leite")
input()
print("1/2 xícara de óleo vegetal")
input()
print("2 colheres de chá de extrato de baunilha")
input()
print("1 xícara de água fervente")
input()
print("\nModo de preparo:")
print("Pré-aqueça o forno a 180°C. Unte uma forma de bolo com manteiga e farinha, ou forre-a com papel manteiga.")
input()
print("Em uma tigela grande, peneire a farinha de trigo, o açúcar, o cacau em pó, o fermento em pó, o bicarbonato de sódio e o sal. Misture bem.")
input()
print("Em outra tigela, bata os ovos levemente. Adicione o leite, o óleo vegetal e o extrato de baunilha. Misture bem.")
input()
print("Despeje os ingredientes líquidos na mistura de ingredientes secos e mexa até que tudo esteja bem combinado.")
input()
print("Adicione a água fervente à massa e misture até que a massa fique homogênea. A massa ficará líquida, mas é normal.")
input()
print("Despeje a massa na forma preparada e leve ao forno pré-aquecido.")
input()
print("Asse por cerca de 30-35 minutos, ou até que um palito inserido no centro do bolo saia limpo.")
input()
print("Retire o bolo do forno e deixe esfriar na forma por alguns minutos. Em seguida, transfira para uma grade de resfriamento para esfriar completamente.")
input()
print("Depois de esfriar, você pode servir o bolo simples ou decorá-lo com cobertura de sua preferência, como ganache de chocolate ou glacê de chocolate.")
input()
